import React from "react";
import {createRoot} from "react-dom/client";
import product from "./generated/product.json";
import design from "./generated/design-ir.json";
import "./styles.css";

type Role="member"|"moderator"|"support";
type Message={id:number;from:"me"|"them";body:string;time:string};
type Plan={id:number;venue:string;time:string;status:"proposed"|"confirmed"|"cancelled";checkIn:boolean};
type Report={id:number;subject:string;summary:string;status:"open"|"reviewing"|"resolved"};
type Store={matched:boolean;messages:Message[];plans:Plan[];verified:boolean;blocked:boolean;reports:Report[];role:Role;profile:{name:string;bio:string};preferences:{distance:number;intent:string}};

const initial:Store={matched:false,messages:[{id:1,from:"them",body:"Your bookshop answer made me smile. What are you reading now?",time:"09:42"}],plans:[],verified:false,blocked:false,reports:[],role:"member",profile:{name:"Mara",bio:"Architect, ceramicist, and devoted city walker."},preferences:{distance:18,intent:"Long-term relationship"}};
let authToken="";
async function loginRole(role:Role){const credentials=role==="moderator"?["moderator","moderator-pass"]:role==="support"?["support","support-pass"]:["mara","member-pass"];const response=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:credentials[0],password:credentials[1]})});if(!response.ok)throw new Error("login failed");const value=await response.json();authToken=value.token}
async function api(path:string,body:Record<string,unknown>={}){const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${authToken}`},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error||`request failed: ${response.status}`);return value}
function useStore(){const [state,setState]=React.useState<Store>(()=>{try{return {...initial,...JSON.parse(localStorage.getItem("pulsematch-state-v1")||"{}")}}catch{return initial}});React.useEffect(()=>localStorage.setItem("pulsematch-state-v1",JSON.stringify(state)),[state]);return [state,setState] as const}
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const icons:Record<string,string>={discover:"✦",matches:"♡",messages:"◌",conversation:"◌",plans:"⌁",plan_detail:"⌁",safety:"◇",profile:"○",preferences:"≡",verification:"✓",subscription:"♢",moderation:"⚑"};

function Pill({children,tone="default"}:{children:React.ReactNode;tone?:string}){return <span className={`pill ${tone}`}>{children}</span>}
function Empty({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <div className="empty"><span>✦</span><h3>{title}</h3><p>{copy}</p>{action}</div>}
function PageHead({kicker,title,copy,action}:{kicker:string;title:string;copy:string;action?:React.ReactNode}){return <header className="page-head"><div><p className="kicker">{kicker}</p><h2>{title}</h2><p>{copy}</p></div>{action}</header>}

function Discover({state,setState,go}:{state:Store;setState:React.Dispatch<React.SetStateAction<Store>>;go:(r:string)=>void}){return <>
 <PageHead kicker="Curated for you" title="Meet with intention." copy="Compatibility you can understand. Safety you never have to ask for." action={<div className="discovery-count"><strong>12</strong><span>thoughtful profiles today</span></div>}/>
 <section className="discovery-layout" data-testid="review_explainable_profile"><article className="profile-card"><div className="portrait portrait-alex"><div className="portrait-copy"><Pill tone="light">Identity verified</Pill><div><h3>Alexandra, 31</h3><p>Cape Town · 4 km away</p></div></div></div><div className="profile-body"><div className="tag-row"><Pill>Architect</Pill><Pill>Slow travel</Pill><Pill>Sunday markets</Pill></div><p className="profile-quote">“I collect beautiful questions, sea-glass, and recipes I’ll probably alter.”</p><div className="profile-actions"><button className="icon-button" aria-label="Pass">×</button><button className="primary round" data-testid="express_interest" onClick={async()=>{await api("/api/matches/interest");setState(s=>({...s,matched:true}));go("matches")}}>{state.matched?"Matched":"Express interest"} <span>♡</span></button></div></div></article>
 <aside className="compat-card"><div className="score-ring"><strong>92</strong><span>% aligned</span></div><div><p className="kicker">Why this could work</p><h3>Rare compatibility</h3></div><ul><li><b>Shared rhythm</b><span>Both protect quiet mornings and social evenings.</span></li><li><b>Intent clarity</b><span>You each selected a long-term relationship.</span></li><li><b>Curiosity</b><span>High overlap in design, food, and local culture.</span></li></ul><button className="text-button">See all compatibility evidence →</button></aside></section>
 </>}

function Matches({state,go}:{state:Store;go:(r:string)=>void}){const cards=[{name:"Alexandra",note:state.matched?"You matched just now":"Suggested for you",tone:"alex"},{name:"Noah",note:"Replied 12m ago",tone:"noah"},{name:"Lindiwe",note:"New match",tone:"lindi"}];return <><PageHead kicker="Connections" title="A smaller, better circle." copy="Mutual interest becomes a conversation—never an obligation."/><div className="match-grid">{cards.map((c,i)=><button className="match-card" key={c.name} onClick={()=>go(i===0?"conversation":"messages")}><div className={`mini-portrait ${c.tone}`}>{c.name[0]}</div><div><h3>{c.name}</h3><p>{c.note}</p></div><span>→</span></button>)}</div></>}

function Messages({go}:{go:(r:string)=>void}){return <><PageHead kicker="Messages" title="Conversations with context." copy="Consent controls, plans, and safety tools stay one tap away."/><section className="inbox"><div className="thread-list"><button className="thread active" data-testid="open_match" onClick={()=>go("conversation")}><div className="avatar alex">A</div><div><b>Alexandra</b><p>Your bookshop answer made me smile…</p></div><time>09:42</time></button>{["Noah","Lindiwe","Sam"].map((x,i)=><button className="thread" key={x}><div className="avatar">{x[0]}</div><div><b>{x}</b><p>{i?"What does your ideal Sunday look like?":"That exhibition sounds perfect."}</p></div><time>{i+1}d</time></button>)}</div><div className="inbox-preview"><p className="kicker">A quieter inbox</p><h3>Messages open only after mutual interest.</h3><p>No cold DMs. No attention games. Every thread begins with shared context.</p><button className="primary" onClick={()=>go("conversation")}>Open conversation</button></div></section></>}

function Conversation({state,setState,go}:{state:Store;setState:React.Dispatch<React.SetStateAction<Store>>;go:(r:string)=>void}){const [body,setBody]=React.useState("");return <><PageHead kicker="Alexandra · matched today" title="A promising beginning." copy="You both chose intentional conversation." action={<button className="ghost" onClick={()=>go("safety")}>Safety & controls</button>}/><section className="conversation"><div className="chat"><div className="day">Today</div>{state.messages.map(m=><div className={`bubble ${m.from}`} key={m.id}><p>{m.body}</p><span>{m.time} {m.from==="me"&&"· Delivered"}</span></div>)}<form onSubmit={async e=>{e.preventDefault();if(!body.trim())return;const text=body.trim();const saved=await api("/api/messages",{match_id:1,body:text});setState(s=>({...s,messages:[...s.messages,{id:saved.id,from:"me",body:text,time:"Now"}]}));setBody("")}}><input aria-label="Message" value={body} onChange={e=>setBody(e.target.value)} placeholder="Write something thoughtful…"/><button data-testid="send_message">Send</button></form></div><aside className="context-panel"><div className="mini-portrait alex">A</div><h3>Alexandra</h3><p>92% compatibility</p><button onClick={()=>go("plans")}>Plan a date</button><dl><dt>Shared value</dt><dd>Curiosity</dd><dt>Conversation cue</dt><dd>Ask about the blue house project</dd></dl></aside></section></>}

function Plans({state,setState,go}:{state:Store;setState:React.Dispatch<React.SetStateAction<Store>>;go:(r:string)=>void}){const [venue,setVenue]=React.useState("The Reading Room");const [time,setTime]=React.useState("Saturday · 16:00");const propose=async()=>{const saved=await api("/api/plans",{venue,starts_at:time});setState(s=>({...s,plans:[...s.plans,{id:saved.id,venue,time,status:"proposed",checkIn:false}]}))};return <><PageHead kicker="Plans" title="Turn intention into a safe plan." copy="Agree on the details, share a check-in, and keep control of what changes."/><section className="plan-layout"><div className="plan-form"><label>Place<input value={venue} onChange={e=>setVenue(e.target.value)}/></label><label>When<input value={time} onChange={e=>setTime(e.target.value)}/></label><label className="check"><input type="checkbox"/> Public place confirmed</label><button className="primary" data-testid="propose_place_and_time" onClick={propose}>Propose this plan</button></div><div className="plan-list">{state.plans.length===0?<Empty title="No plans yet" copy="A thoughtful invitation will appear here."/>:state.plans.map(p=><article key={p.id}><Pill tone={p.status}>{label(p.status)}</Pill><h3>{p.venue}</h3><p>{p.time}</p><div className="inline-actions"><button data-testid="share_check_in" onClick={async()=>{await api(`/api/plans/${p.id}/checkin`);setState(s=>({...s,plans:s.plans.map(x=>x.id===p.id?{...x,checkIn:true}:x)}))}}>{p.checkIn?"Check-in shared":"Share safety check-in"}</button><button data-testid="confirm_plan" onClick={async()=>{await api(`/api/plans/${p.id}/confirm`);setState(s=>({...s,plans:s.plans.map(x=>x.id===p.id?{...x,status:"confirmed"}:x)}));go("plan_detail")}}>Confirm</button></div></article>)}</div></section></>}

function PlanDetail({state,go}:{state:Store;go:(r:string)=>void}){const plan=state.plans.at(-1);return <><PageHead kicker="Confirmed plan" title={plan?.venue||"Your next plan"} copy={plan?.time||"The details will appear once you confirm."}/>{plan?<section className="detail-card"><div className="map-art"><span>⌖</span></div><div><Pill tone="confirmed">Confirmed</Pill><h3>Everything in one calm place</h3><ul className="checklist"><li>✓ Public venue</li><li>✓ Both people confirmed</li><li>{plan.checkIn?"✓":"○"} Trusted contact check-in</li></ul><button className="ghost" onClick={()=>go("conversation")}>Back to conversation</button></div></section>:<Empty title="No confirmed plan" copy="Confirm a plan first."/>}</>}

function Safety({state,setState}:{state:Store;setState:React.Dispatch<React.SetStateAction<Store>>}){const [summary,setSummary]=React.useState("Repeated unwanted contact after I asked to pause.");return <><PageHead kicker="Trust & safety" title="Your boundaries are product behavior." copy="Block instantly, preserve evidence, and make an attributed report without losing context."/><div className="safety-grid"><article><span className="feature-icon">◇</span><h3>Block contact</h3><p>Ends messaging immediately and removes your profile from their discovery.</p><button data-testid="confirm_block_and_audit" onClick={async()=>{await api("/api/blocks");setState(s=>({...s,blocked:true}))}}>{state.blocked?"Blocked · audit saved":"Block Alexandra"}</button></article><article><span className="feature-icon">⚑</span><h3>Report with context</h3><textarea value={summary} onChange={e=>setSummary(e.target.value)} aria-label="Report summary"/><button data-testid="submit_attributed_report" onClick={async()=>{const saved=await api("/api/reports",{summary});setState(s=>({...s,reports:[...s.reports,{id:saved.id,subject:"Alexandra",summary,status:"open"}]}))}}>Submit attributed report</button>{state.reports.length>0&&<p data-testid="report_submitted">Report submitted · evidence preserved</p>}</article><article><span className="feature-icon">⌁</span><h3>Share a check-in</h3><p>Your trusted contact sees plan timing—not your private messages.</p><button>Manage trusted contacts</button></article></div></>}

function Profile({state,setState}:{state:Store;setState:React.Dispatch<React.SetStateAction<Store>>}){return <><PageHead kicker="Profile" title="Be specific enough to be known." copy="Your profile should start better conversations, not collect impressions."/><section className="editor"><div className="portrait portrait-me"><span>M</span></div><div className="form-stack"><label>Display name<input value={state.profile.name} onChange={e=>setState(s=>({...s,profile:{...s.profile,name:e.target.value}}))}/></label><label>About you<textarea value={state.profile.bio} onChange={e=>setState(s=>({...s,profile:{...s.profile,bio:e.target.value}}))}/></label><button className="primary">Save profile</button></div></section></>}

function Preferences({state,setState}:{state:Store;setState:React.Dispatch<React.SetStateAction<Store>>}){return <><PageHead kicker="Preferences" title="Tune for compatibility, not volume." copy="These controls shape who enters your considered set."/><section className="settings-card"><label>Relationship intention<select value={state.preferences.intent} onChange={e=>setState(s=>({...s,preferences:{...s.preferences,intent:e.target.value}}))}><option>Long-term relationship</option><option>Exploring intentionally</option><option>Friendship first</option></select></label><label>Distance · {state.preferences.distance} km<input type="range" min="2" max="80" value={state.preferences.distance} onChange={e=>setState(s=>({...s,preferences:{...s.preferences,distance:Number(e.target.value)}}))}/></label><div className="toggle-row"><div><b>Verified profiles first</b><p>Prioritize people who completed identity checks.</p></div><input type="checkbox" defaultChecked/></div><div className="toggle-row"><div><b>Compatibility explanations</b><p>Show why a profile was selected.</p></div><input type="checkbox" defaultChecked/></div></section></>}

function Verification({state,setState}:{state:Store;setState:React.Dispatch<React.SetStateAction<Store>>}){return <><PageHead kicker="Identity verification" title={state.verified?"You’re verified.":"Trust starts with a real person."} copy="A private identity check earns a public verification mark. Documents are never shown to matches."/><section className="verification-card"><div className={`verify-seal ${state.verified?"done":""}`}>{state.verified?"✓":"◇"}</div><ol><li className="done"><span>1</span><div><b>Account secured</b><p>Email and device confirmed</p></div></li><li className={state.verified?"done":"active"}><span>2</span><div><b>Identity evidence</b><p>Government ID and a live pose</p></div></li><li className={state.verified?"done":""}><span>3</span><div><b>Verification decision</b><p>Usually within a few minutes</p></div></li></ol><button className="primary" data-testid={state.verified?"observe_verified_state":"submit_evidence"} onClick={async()=>{await api("/api/verification");setState(s=>({...s,verified:true}))}}>{state.verified?"Verified evidence receipt":"Submit evidence securely"}</button></section></>}

function Subscription(){return <><PageHead kicker="Membership" title="Pay for depth, never pressure." copy="Core matching and safety stay free. Membership adds control and reflection."/><div className="pricing"><article><p>Essential</p><h3>Free</h3><ul><li>Curated discovery</li><li>Unlimited mutual conversations</li><li>All safety tools</li></ul><button>Current plan</button></article><article className="featured"><Pill tone="light">Most intentional</Pill><p>Pulse+</p><h3>R189 <small>/ month</small></h3><ul><li>Advanced compatibility evidence</li><li>Private profile review</li><li>Travel and pause modes</li></ul><button className="primary">Choose Pulse+</button></article></div></>}

function Moderation({state,setState}:{state:Store;setState:React.Dispatch<React.SetStateAction<Store>>}){if(state.role!=="moderator")return <div className="forbidden" data-testid="moderation_forbidden"><span>◇</span><h2>Moderator workspace</h2><p>This evidence queue is isolated from member access.</p></div>;return <><PageHead kicker="Moderation" title="Evidence before judgment." copy="Every decision is bounded, attributed, and auditable."/><section className="moderation"><div className="queue">{state.reports.length?state.reports.map(r=><button key={r.id}><Pill tone={r.status}>{r.status}</Pill><b>{r.subject}</b><p>{r.summary}</p></button>):<Empty title="Queue is clear" copy="No open member reports."/>}</div><article className="evidence-review"><p className="kicker">Decision workspace</p><h3>Review attributed evidence</h3><div className="evidence-line"><span>09:42</span><p>Member asked contact to pause.</p></div><div className="evidence-line"><span>10:11</span><p>Additional message was delivered.</p></div><label>Bounded outcome<select><option>Warn and restrict contact</option><option>Temporary suspension</option><option>No action — insufficient evidence</option></select></label><button className="primary" data-testid="record_bounded_decision" onClick={async()=>{const report=state.reports.at(-1);if(report)await api(`/api/reports/${report.id}/decision`,{decision:"warn_and_restrict"});setState(s=>({...s,reports:s.reports.map(r=>({...r,status:"resolved"}))}))}}>Record decision + audit</button></article></section></>}

function App(){const [state,setState]=useStore();const [ready,setReady]=React.useState(false);const routes=(product.routes as {id:string}[]).map(r=>r.id);const [active,setActive]=React.useState(()=>location.hash.slice(1)||routes[0]);const [apiError,setApiError]=React.useState(false);const go=(route:string)=>{setActive(route);location.hash=route;scrollTo(0,0)};React.useEffect(()=>{loginRole(state.role).then(()=>setReady(true)).catch(()=>setApiError(true))},[]);React.useEffect(()=>{const f=()=>setActive(location.hash.slice(1)||routes[0]);addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[routes.join()]);if(!ready)return <div className="boot"><span>♡</span><p>Opening your private workspace…</p></div>;let view:React.ReactNode;switch(active){case"discover":view=<Discover state={state} setState={setState} go={go}/>;break;case"matches":view=<Matches state={state} go={go}/>;break;case"messages":view=<Messages go={go}/>;break;case"conversation":view=<Conversation state={state} setState={setState} go={go}/>;break;case"plans":view=<Plans state={state} setState={setState} go={go}/>;break;case"plan_detail":view=<PlanDetail state={state} go={go}/>;break;case"safety":view=<Safety state={state} setState={setState}/>;break;case"profile":view=<Profile state={state} setState={setState}/>;break;case"preferences":view=<Preferences state={state} setState={setState}/>;break;case"verification":view=<Verification state={state} setState={setState}/>;break;case"subscription":view=<Subscription/>;break;case"moderation":view=<Moderation state={state} setState={setState}/>;break;default:view=<Empty title="Route unavailable" copy="Return to discovery."/>}
return <div className={`app ${design.design_language} density-${design.density}`}><aside className="sidebar"><button className="wordmark" onClick={()=>go("discover")}><span>pulse</span>match<i>♡</i></button><nav aria-label="Primary navigation">{routes.map(route=><button key={route} data-route={route} className={active===route?"active":""} onClick={()=>go(route)}><span>{icons[route]||"·"}</span>{label(route)}</button>)}</nav><div className="trust-mini"><span>✓</span><div><b>Safety center</b><p>Controls always available</p></div></div></aside><div className="stage"><header className="topbar"><div className="search">⌕ <input aria-label="Search" placeholder="Search matches, messages, plans…"/></div><div className="top-actions"><button className="status" data-testid="simulate-api-failure" onClick={()=>setApiError(true)}><i/> Systems healthy</button><select aria-label="Demo role" value={state.role} onChange={async e=>{const role=e.target.value as Role;await loginRole(role);setState(s=>({...s,role}))}}><option value="member">Member</option><option value="moderator">Moderator</option><option value="support">Support</option></select><button className="avatar me">M</button></div></header>{apiError&&<div className="error-banner" data-testid="api_error">We couldn’t refresh your latest data. Your saved work is safe.<button data-testid="retry_api" onClick={()=>setApiError(false)}>Retry now</button></div>}<main>{view}</main><footer><span>PulseMatch · explainable compatibility</span><span>Privacy · Conduct · Safety</span></footer></div></div>}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
